# -*- coding: utf-8 -*-
"""emotions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11PGUgn6M6Zt648MmhAVAevTjd0j1Q-fO
"""

import pandas as pd
import csv
import os

current_path = os.getcwd()

class Emotion():
    def __init__(self, document):
        self.document = document
        self.score = {'anger':[],
                      'anticipation':[],
                      'disgust':[],
                      'fear':[],
                      'joy':[],
                      'sadness':[],
                      'surprise':[],
                      'trust':[]}
        self.average = {'anger':0,
                      'anticipation':0,
                      'disgust':0,
                      'fear':0,
                      'joy':0,
                      'sadness':0,
                      'surprise':0,
                      'trust':0 
        }
    def calculateEmotionScore(self):
        doc = self.document
        #read lookup table
        datas = []
        with open("NRC.csv", 'r') as file:
            csvreader = csv.reader(file)
            header = next(csvreader)
            for row in csvreader:
                datas.append(row)
        for token in doc:
            for data in datas:
                if data[0] == token and data[1] == 'anger':
                    # print(token + " anger")
                    self.score['anger'].append(float(data[2]))
                if data[0] == token and data[1] == 'anticipation':
                    # print(token + " anticipation")
                    self.score['anticipation'].append(float(data[2]))
                if data[0] == token and data[1] == 'disgust':
                    # print(token + " disgust")
                    self.score['disgust'].append(float(data[2]))
                if data[0] == token and data[1] == 'fear':
                    # print(token + " fear")
                    self.score['fear'].append(float(data[2]))
                if data[0] == token and data[1] == 'joy':
                    # print(token + " joy")
                    self.score['joy'].append(float(data[2]))
                if data[0] == token and data[1] == 'sadness':
                    # print(token + " sadness")
                    self.score['sadness'].append(float(data[2]))
                if data[0] == token and data[1] == 'surprise':
                    # print(token + " surprise")
                    self.score['surprise'].append(float(data[2]))
                if data[0] == token and data[1] == 'trust':
                    self.score['trust'].append(float(data[2]))
                    
    def calculateAverage(self):
        emos = ['anger','anticipation','disgust','fear','joy','sadness', 'surprise', 'trust']
        for emo in emos :
            if len(self.score[emo]) == 0:
                self.average[emo] = 0
            else :
                self.average[emo] = sum(self.score[emo])/len(self.score[emo])
    
    def getScoreMatrix(self):
        self.calculateEmotionScore()
        self.calculateAverage()
        res = [i for i in self.average.values()]
        return res
#testcase = "brand new teenager peeing you don ' t know me from adam . : ) iyakubonana that you have not given away will ever be really yours . I don ' t deserve this award , but i have arthritis , and i don ' t deserve that , either . the most important thing a father can do for his children is to love their mother . tricks and treachery are the practice of fools , that don ' t have brains enough to be honest . a heart that loves is always young . if you drink , don ' t drive . don ' t even putt . husbands never become good they merely become proficient . only from the heart can you touch the sky . neven if it is to be , what end do you serve by running to distress ? it is a terrible thing to look over your shoulder when you are trying to lead - - and find no one there . i hated her now with a hatred more fatal than indifference because it was the other side of love . reading makes a full man , meditation a profound man , discourse a clear man . a few strong instincts and a few plain rules suffice us . we are all sentenced to solitary confinement inside our own skins , for life . eroticism is assenting to life even in death . truly great friends are hard to find , difficult to leave , and impossible to forget . the weeping of an heir is laughter in disguise . the harder i work the luckier i get ."
#testcase = "brand teenager peeing don adam iyakubonana don deserve award arthritis don deserve father children love mother tricks treachery practice fools don brains honest heart loves drink don drive don putt husbands merely proficient heart touch sky serve running distress terrible look shoulder trying lead hated hatred fatal indifference love reading makes meditation profound discourse strong instincts plain rules suffice sentenced solitary confinement inside own skins life eroticism assenting life death truly friends hard difficult leave impossible forget weeping heir laughter disguise harder luckier"
#testcase = "kin attn dear sir madam am michael fisher charge bills foreign exchange remittance department barclay bank am writing letter support co operation carry business opportunity department discovered unclaimed sum million twenty million five hundred thousand british pounds sterling account belonging customer died car crash entire family information death expecting kin claim money unfortunately neither family nor relation appeared claim money release money unless applies kin relation deceased banking guidelines indicated money remained unclaimed period transferred barclay bank treasury unclaimed fund officer department decided transfer money account kin relation deceased easy collection coming don money bank treasury unclaimed debt friend advised urgently arrange transfer money foreign beneficiary outside country decided total sum please matter urgency send telephone fax effective communication conclude transaction successfully time please send immediate mail explain details understand business waiting urgent response thank michael fisher send relies private mail box michaelfisher walla com"
#testcase = "time sensitive refer hi sent email week confirm please review info below questions happy inform accepting mo rtgage application bad cr edit ok ready loa month payment appr oval process minute visit link below fill short form thank partid moffob regards ceo santos gorman lst union financiers future correspondence choices landrater net st html"
#testcase = "notification bequest dr abdul kareem kareem co solicitors advocates akin osiyemi ikeja lagos nigeria tel ab karol fastermail com notification bequest sequel response earlier letter behalf trustees executors late sir engr john scott ksm wish notify listed beneficiary bequest sum million hundred thousand dollars codicil testament deceased late sir engr john scott death former managing director pioneer staff construction company julius berger nigeria dedicated christian philanthropist life time late sir john scott died th february age buried rd february late sir john scott american living foreigner requested death buried words regard home people people token support ministry help privilegded hereby request forward proof identities current telephone fax forwarding address private mail box ab karol fastermail com enable file documents court probate division release bequest money congratulations faithfully dr abdul kareem san"
#testcase = "re ye fagott jabbed free cable tv drudge plenipotentiary spend dahlia crimea homeowner lura moonlit depressive brian pebble pentane haddad decaffeinate celtic immoderate fungi asteroidal transliterate border wizard laminar afterimage ream muffle bluegrass sprawl arrowroot act usurpation acquit wily cupboard dante kindred zigzag morel pagan emendable tabular recession sleigh chic monetary algorithm autocrat offertory lid abrade atchison agreeing milieu chivalrous distal corporeal cutset plaque loudspeaker shaken saloonkeep trilogy"
#t = "york etc am checking russell mom passed friday funeral tomorrow tuesday lubbock texas am trying arrangements attend doesn look probable due flights input canceling ny trip appreciate support letting proceed remaining benefit calm nerves set course understand able attend public belief pec keyspan enron employees job week believe entirely inappropriate doing celebratory deemed ruthless call immediately spent incremental reviving event mail ensure ena retains deirdre mccaffrey currently freight please move investment firm approached inquiry enovate sign confidentiality discuss conversation week received package home productive help laura"
#t = "re green card process louise tell excited am pleasure saying am taking time bought travel trailer getting ready deer lease ve decided authority finally complete ll dinner tell framer items frame road son christmas stocking complete traveling lot flights stitching time thanks am excited regards bobbi international human resources telephone space eb fax original message kitchen louise sent thursday october pm tessandori bobbi nettelton marcus re green card process thanks wow blue marcus scott appreciate louise original message tessandori bobbi sent thursday october pm kitchen louise nettelton marcus green card process louise marcus received confirmation tindall foster news report time louise congratulations powerful women business complement women thank inspiration women girls am proud blue regards bobbi international human resources telephone space eb fax"
#t = "re canadian legal entity mich kelly dawn phone assign ee original message kitchen louise sent friday february pm oxley david fw canadian legal entity contracts original message forster david sent friday february pm taylor mark legal keohane peter hedstrom peggy cc kitchen louise milnthorp rob beck sally zufferli john canadian legal entity name canadian entity enter master agreements individual commodity transactions ubs warburg energy canada ltd confirmed lou eber ubs chief legal counsel am chasing parental guarantee issue dave"
#t = "cpuc votes suspend direct access september fanfare except commissoner wood continued vitriolic attack da green choice fraudulent language da contracts entered directs utilities police dasrs none submitted contracts signed strange language talks future address comments raised parties putting parties notice future suspend direct access contracts signed july attorneys reviewing blush california attorney cpuc difficult time implementing retroactive suspension da"
t = "fw exelon meeting chicago based ees people attending meeting tariff prices ie ews hate expense ees ledger original message herndon rogers sent monday july pm presto kevin fw exelon meeting chicago kevin fyi tripping ourselves probably meeting marc ulrich jeff merola fine views rogers original message herndon rogers sent monday july pm migden janine exelon meeting chicago janine confirm people attending meeting getting little bringing people add significant value actual meeting count follows marc ulrich urm commercial expert comed rate effects business mandatory jeff merola manager physical delivery logistics central region mandatory brad snyder structured supply mark bernstein structured supply jeff ader structured supply janine migden regulatory roy boston regulatory rogersherndon ews risk name forgot legal ulrich recomended comed audience agenda items comed ppo phase intentions physical delivery issues potential business transactions comed enron trim list attendees"
emo = Emotion(t.split())
numeric_emotion = emo.getScoreMatrix()
print("hasil ", numeric_emotion)
